### PR TITLE
Feature/refactor covariance displays

### PR DESCRIPTION
**Pull request by Ellon**
In this PR I re-factored the plugin's Pose and Odometry displays to enable back all the functionalities from the original rviz displays, in a way that the covariance looks like more or less like an addon to the original displays. This PR is based on the code from #9.

The computation of the covariances are the same as before, but just wrapped into one file (covariance_visual.cpp). The covariance visualization is also the same (ellipse for position and a cone (?) for orientation). I think this way it's easy to improve the drawing of the covariances later.

One thing I did was to add some functionality from Pose to Odometry, like possibility to visualize the odometry as arrow or axes, and a finer control of the shapes being draw (axis length and radius, and arrows shaft/head length/radius). The selection tool for the pose with covariance is also working.

### CODE REVIEW

**Comment by georgebrindeiro** [comment]
Looks good to me

**Comment by v01d** [comment]
Can this be merged and then any subsequent improvements be proposed in new PRs? Integrating this would this package to be used, which is not possible ATM due to the wrong results of the ellipse orientation.

**Comment by Ellon** [comment]
@v01d It doesn't look this thread is being watched by any maintainers... Maybe @thomas-moulard or @mherrb could take a look at it?

**Comment by mherrb** [comment]
If Thomas is still interested, let him validate this. If he doesn't answer in a few days, I will take care of it (or just give you access to the repository)

**Comment by thomas-moulard** [comment]
Hi all, thank for waiting for my input!

@mherrb could please go ahead and merge this? I don't have any write-access to the repo anymore and I don't use ROS for my work currently so I don't have the bandwidth to maintain this plugin.

IMHO the best thing to do is to send this as a PR to rviz and see if we can get this included by default. Last time we checked the maintainers seemed to be willing to accept it.

**Comment by thomas-moulard** [comment]
BTW if rviz integration is not an option but someone is interested to maintain this code. Please check with @mherrb . On my side, I don't have any objection to have anyone take over this repo. Thanks!

**Comment by Ellon** [comment]
Hello Thomas, thanks for the input. I plan to send this as a PR to rviz later, after I have the angular covariances being displayed properly.

**Comment by wjwwood** [comment]
Hi guys. I found my way over here from https://github.com/ros-visualization/rviz/pull/974. My slight preference is to get this working here first and then propose merging this into rviz after people agree that it is working correctly. The idea being that people who are already using this as an external plugin can benefit from the improvements too. I'd probably only consider this plugin for merging into Jade or Kinetic. If merging went well for those versions then I'd consider Indigo, but it won't be a quick turn around.

Thanks!

**Comment by Ellon** [comment]
OK @wjwwood I'll update [](https://github.com/ros-visualization/rviz/pull/974)

**Comment by mherrb** [comment]
Hi Ellon, I've merge the request and added you as team member for this repository. You can now manage it directly.

**Comment by Ellon** [comment]
Ok @mherrb , Thanks!

**Comment by NikolausDemmel** [comment]
Looks like I'm late to the party... @Ellon: We are using this plugin. Thanks for the update, i will give it a try shortly.

**Comment by NikolausDemmel** [comment]
So it works quite nicely! Thank you very much @Ellon for cleaning this up, and fixing the reference frames as well as the eigen vector order.

I have some comments, but they are of a more general nature, so I will add them over at #10.

**Comment by NikolausDemmel** [comment]
P.S.: +1 for getting this into rviz proper, even indigo, and discutinuing development here.

**Comment by wjwwood** [comment]
Now that the issues are sorted out here, I'll take a look at the rviz pr. I just wanted to separate the concern of fixing the thing and getting it put into rviz.

Also, since I take on some level of maintenance when things are merged into rviz, so I tend to review it carefully before rolling it in.

**Comment by Ellon** [comment]
Er... in fact there are still some issues I just opened, mostly related with 2D poses and rotational covariance. Please check #10 and the currently open issues.

**Pull request merged**
