### PR TITLE
Fix 2D poses

### LINKED ISSUE #12: Covariance for 2D poses not being displayed properly
Opening the issue as a reminder, based on https://github.com/laas/rviz_plugin_covariance/issues/10#issuecomment-191264433 and https://github.com/laas/rviz_plugin_covariance/issues/10#issuecomment-191287385.

### PR DESCRIPTION
**Pull request by Ellon**
This PR fixes #12 .

Poses 2D are identified as having the elements z, roll and pitch of the covariance matrix's diagonal set to negative. The maximum standard deviation on yaw is set to 85 degrees.

I'll let this PR open for a few days for testing before merging it on indigo branch.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
As mentioned in https://github.com/laas/rviz_plugin_covariance/issues/10#issuecomment-191501764, I think it would be great if 2D covariances would be supported implicitely by the fact that one or multiple eigenvalues of the covariance are 0. At least for position this seems to already be the case (maybe we should actually test a "tilted" 2D covariance that as 0 variance not along one of the three main axes). Rotational covariance needs fixing anyway, which is tracked in #13, so we should just keep the 2D case in mind there.

I have not seen the -1 convention for indicating 2D poses. Can we find a reference for it? But I guess it should not really hurt, even if the same can be achieved with 0s.

**Comment by Ellon** [comment]
I change the definition of a pose 2D for the one you suggested. Could you test it and see if it's ok?

**Comment by Ellon** [comment]
Just updated this PR with the work made on top of #15 . @NikolausDemmel Does it look good for your 2D visualization?

**Comment by Ellon** [comment]
pose2d_1
pose2d_2

**Comment by NikolausDemmel** [comment]
Cool stuff. I'll give it a try shortly.

**Pull request merged**
